### ISSUE TITLE
feature request: re-tail identically named resource

### ISSUE THREAD

**Issue by gretel** [knight42/kt#3]
```
- [example-pod-kvfr5] pod deleted
```

now, i'd be awesome if `kt` could pickup logging if a identically named resource comes up:

 * detect resource deletion
 * wait (in configurable intervals) for the resource to show up
 * tail, again

why? i'm working on a interactive workflow for https://github.com/GoogleContainerTools/kaniko requiring something like as described above..

**Comment by knight42** [comment]
@gretel now `kt` should be able to work as you described.

For example, let's say we have a pod running as shown below:
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-log
  name: test-log
spec:
  containers:
  - image: alpine:3.10
    name: test-log
    command:
    - sh
    - -c
    - 'while true; do date; sleep 3; done'
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
```

and we execute `kt test-log` in a terminal. 

Then if we recreate this pod, `kt` should auto re-tail it:

```
$ kt test-log
+ [test-log] pod added
test-log[test-log] Mon Feb 17 11:53:09 UTC 2020
test-log[test-log] Mon Feb 17 11:53:12 UTC 2020
test-log[test-log] Mon Feb 17 11:53:15 UTC 2020
test-log[test-log] Mon Feb 17 11:53:18 UTC 2020
test-log[test-log] Mon Feb 17 11:53:21 UTC 2020
test-log[test-log] Mon Feb 17 11:53:24 UTC 2020
test-log[test-log] Mon Feb 17 11:53:27 UTC 2020
test-log[test-log] Mon Feb 17 11:53:30 UTC 2020
test-log[test-log] Mon Feb 17 11:53:33 UTC 2020
test-log[test-log] Mon Feb 17 11:53:36 UTC 2020
test-log[test-log] Mon Feb 17 11:53:39 UTC 2020
test-log[test-log] Mon Feb 17 11:53:42 UTC 2020
test-log[test-log] Mon Feb 17 11:53:45 UTC 2020
test-log[test-log] Mon Feb 17 11:53:48 UTC 2020
test-log[test-log] Mon Feb 17 11:53:51 UTC 2020
- [test-log] pod deleted
+ [test-log] pod added
test-log[test-log] Mon Feb 17 11:54:15 UTC 2020
test-log[test-log] Mon Feb 17 11:54:18 UTC 2020
test-log[test-log] Mon Feb 17 11:54:21 UTC 2020
^C
```

**Comment by gretel** [comment]
@knight42 thanks! just tried, but does not pickup the pod, again.

**Comment by knight42** [comment]
@gretel could you let me know the commands you executed?

**Comment by gretel** [comment]
job description:

```
$ kubectl describe job kaniko-kerykeion
Name:           kaniko-kerykeion
Namespace:      ca
...
Labels:         app.kubernetes.io/instance=kaniko-kerykeion
                app.kubernetes.io/managed-by=Helm
                app.kubernetes.io/name=kaniko
                app.kubernetes.io/version=0.17.1
                helm.sh/chart=kaniko-0.3.6
Annotations:    helm.sh/hook: post-install,post-upgrade
...
```

works, but does not pick up recreated job:

```
$ kt -v3 -n ca --tail 10 job kaniko-kerykeion
+ [kaniko-kerykeion-p627h] pod added
kaniko-kerykeion-p627h[build] INFO[0010] RUN curl -sSL https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz | tar -xzO linux-amd64/helm -f - > /usr/local/bin/helm     && chmod +x /usr/local/bin/helm
...
```

filtering by label (as described) does not work:

```
$ kt -n ca --tail 10 -l app.kubernetes.io/name=kaniko
no matched pods found
```

**Comment by knight42** [comment]
Ah got it, I could fix it soon.

**Comment by gretel** [comment]
@knight42 that'd be awesome!

**Comment by knight42** [comment]
@gretel The problem may be a bit tricky than I expected. The mechanism that `kt` find out the pods belong to a job is filtering pods by labels specifed in `job.spec.selector.matchLabels`, which is sth like:
```
spec:
  selector:
    matchLabels:
      controller-uid: ac8cb0ea-5174-11ea-9cd8-b22a251591f2
```

A newly created job ususally has different uid, so `kt` cannot find out the pods belong to the new job.

The workaround of this problem could be one of:
1. specify labels in the podTemplate of job and execute `kt -n ca -l <selector>`
2. filter pods by regexp, like `kt -n ca kaniko-kerykeion`
